[package]
name = "dbus-marshal"
version = "0.1.0"
edition = "2024"

[features]
default = ["alloc"]
alloc = []

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
static_assertions = "1.1.0"
thiserror = { version = "2.0.18", default-features = false }
